[build]
  base = "kemish-portfolio"
  command = "npm run build"
  publish = ".node"

[functions]
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-nodejs"


[[redirects]]
  from = "/*"
  to = "/"
  status = 200
